### ISSUE TITLE
Requests not placed into folders

### ISSUE THREAD

**Issue by salvo1404** [thecopy/apiary2postman#11]
![screenshot_apiary2postman](https://cloud.githubusercontent.com/assets/5450842/9190949/f317f5c6-403e-11e5-8f91-a7853abed9b9.png)

apiary2postman --only-collection api my_api > postman.collection

**Comment by thecopy** [comment]
Fixed by ec046c6e4b53893d4eafe5d47e4cd1146e5a5b51
