### ISSUE TITLE
Dependencies confusion

### ISSUE THREAD

**Issue by DataGreed** [thecopy/apiary2postman#2]
Hi, I believe it would be better to include prerequisites in the "installation section" - I've missed it at first and was having an error "no such file or directory" – it actually took me some time to understand that there is nothing wrong with my file paths, and that the snowcrash was not installed.

Another suggestion: if snowcrash import fails it would be bice to raise an error, that explicitly says something like "Couldn't find snowcrash, please install it to use apiary2postman"

Though, that's a great tool, thank you!

**Comment by itsjamie** [comment]
Most likely you had redirected your output to a file.
