### ISSUE TITLE
Invalid build instructions for drafter

### ISSUE THREAD

**Issue by vrehak** [thecopy/apiary2postman#23]
apiary2postman prints instructions:

By source:
	git clone https://github.com/apiaryio/drafter
	cd drafter
	git checkout b3dce8d # This is the commit for release 0.1.9
	./configure
	make
	sudo make install

This instructions are wrong. Drafter needs git clone --recursive (see https://github.com/apiaryio/drafter#build), otherwise the build fails with
/usr/bin/python: can't open file 'ext/snowcrash/tools/gyp/gyp_main.py': [Errno 2] No such file or directory

**Comment by bhargav3** [comment]
Add `--recursive` git switch while cloning the drafter repo.

By source:
````
git clone https://github.com/apiaryio/drafter --recursive
cd drafter
git checkout b3dce8d # This is the commit for release 0.1.9
./configure
make
sudo make install
````

**Comment by thecopy** [comment]
You might have an old version, as @bhargav3 said the instructions in the latest version take this into consideration.
