### ISSUE TITLE
Postman -> How to store the response of the request in the text file.

### ISSUE THREAD

**Issue by atulparate** [thecopy/apiary2postman#25]
Hello,

This is related to the POSTMAN + web-service testing. I need the code which we can use to store the response of the request in the text file and then we can transfer that as an input to the next request.

Could anyone help me on this.

Thanks,
Atul S Parate

**Comment by david-espinosa** [comment]
Have you have tried Dredd for API testing? That you want to do is very easy using it's hook.

https://dredd.readthedocs.io/en/latest/hooks-nodejs/

**Comment by atulparate** [comment]
Thanks for the suggestion. I will definitely take a look of it.
