### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by o5** [thecopy/apiary2postman#26]
Hello,

any plans to wrap this tool by Docker? I can help if you want.

Thanks Peter

**Comment by thecopy** [comment]
Hello,

What do you mean? Can't you just do "pip install apiary2postman"
inside your Dockerfile?

2017-01-17 11:22 GMT+01:00, Petr Bugyík <notifications@github.com>:

**Comment by o5** [comment]
Yes exactly, but the Dockerfile should be in your repo and some CI (like Travis) should build & push into official docker registry. 

Then, I can use your tool without installing any of dependencies (python, drafter, C++ build tools, etc) via `docker run -i thecopy/apiary2postman blueprint some.blueprint > postman.dump`.  I recently solved it in my repo [apib2json](https://goo.gl/RJRJnZ), you can check it :)

**Comment by thecopy** [comment]
I understand. This is not something that will be hosted in this repo. I suggest you fork thecopy/apiary2postman and put it on your fork if you really want it.

**Comment by o5** [comment]
> This is not something that will be hosted in this 

Really? We are talking about two new files `Dockerfile` and `.travis.yml`.

**Comment by thecopy** [comment]
Yes, it is two files but it is also life-time maintinance of support
for something i am not an expert in. If you feel it is such a small
thing, feel free to fork and do it yourself.

2017-01-17 13:55 GMT+01:00, Petr Bugyík <notifications@github.com>:
