### ISSUE TITLE
Collection undefined

### ISSUE THREAD

**Issue by Wideshanks** [thecopy/apiary2postman#7]
When I convert my API blueprint to a Postman collection and then run newman, I get a "Collection undefined" in the summary:

![image](https://cloud.githubusercontent.com/assets/2061925/5633473/d02e77f4-95a5-11e4-9209-f41924c01c9b.png)

Through trial and error, I found that if I add an `order` element in the top-level object inside  `collection.json`:

![image](https://cloud.githubusercontent.com/assets/2061925/5633484/e669e01c-95a5-11e4-941f-b64bd846d455.png)

I get the folder listing that I would expect. The screenshot at the top is me running newman twice in a row and, before the second run, modifying `collection.json` in another window to add the `order`.

Any idea why the `order` isn't getting made when I convert from blueprint?

**Comment by thecopy** [comment]
Hello,

Please see PR #6 , it was merged a day ago. Use pip to upgrade it should solve this problem

**Comment by thecopy** [comment]
@Wideshanks This is strange, if adding the order-property manually makes it work then  postman2apiary adding it should _also_ make it work. 

Do you have any more info in this?
