### ISSUE TITLE
Upgrade to drafter

### ISSUE THREAD

**Issue by crisp2u** [thecopy/apiary2postman#8]
Hi,

Any chance to update to [drafter](https://github.com/apiaryio/drafter)  ?  Snowcrash cannot be installed anymore as CLI. It looks like just a replacement.

**Comment by stephen-james** [comment]
+1

**Comment by edersohe** [comment]
+1

**Comment by thecopy** [comment]
Fixed in ecdd3e0222869509eebd50124a8be9b9e46e2a88
