### ISSUE TITLE
Each request must have the same collectionId as the root collection object

### ISSUE THREAD

**Issue by salvo1404** [thecopy/apiary2postman#9]
![screenshot_postman](https://cloud.githubusercontent.com/assets/5450842/8920621/a1967bae-350e-11e5-9feb-8d13fc95f50a.png)

After 
apiary2postman --only-collection api my_api > postman.collection

I got this error when importing the collection in Postman.
any reason why?
I'm on Ubuntu 15.04.
thank you.

**Comment by thecopy** [comment]
Are you using the latest version?
This line: https://github.com/thecopy/apiary2postman/blob/master/apiary2postman/converter.py#L163 are assigning each request to have the same collectionId as the collection object.

**Comment by salvo1404** [comment]
Thank you for your response.
Yes I'm using 0.4.6.
The problem is line https://github.com/thecopy/apiary2postman/blob/master/apiary2postman/converter.py#L16
in which you set a new ID instead of getting the ID from the collection.
I just added this line 
result['id'] = collection['id']
in this for cicle https://github.com/thecopy/apiary2postman/blob/master/apiary2postman/converter.py#L26

**Comment by thecopy** [comment]
Will release 0.4.7 with this hotfix
